# Generated by Django 5.1.3 on 2024-11-25 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='updated_at',
            new_name='last_modified',
        ),
        migrations.RemoveField(
            model_name='document',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='document',
            name='title',
        ),
        migrations.AddField(
            model_name='document',
            name='name',
            field=models.CharField(default='UntitlednUnmastered Document', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='content',
            field=models.TextField(default=''),
        ),
    ]
