# Generated by Django 5.1.3 on 2024-11-26 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0002_rename_updated_at_document_last_modified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='add_buffer',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='document',
            name='original_buffer',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='document',
            name='pieces',
            field=models.TextField(blank=True, default='[]'),
        ),
        migrations.AlterField(
            model_name='document',
            name='content',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='document',
            name='name',
            field=models.CharField(default='Untitled Document', max_length=255, unique=True),
        ),
    ]
